name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 * * * *"   # Runs every 1 hour
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Keep app alive (empty commit)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "keepalive: prevent Streamlit sleep"
          git push
